name: Events Demo 1
on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - 'dev-*'
      - 'feat/**'
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*' # this doesn't allow slashes. eg. dev-new  dev-this-is-new
      - 'feat/**' # 2 asterisks mean that the branch names can have any number of slashes feat/new  feat/new/page/widget
      # developer-1
    paths-ignore:
      - '.github/workflows/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
